
version: '3.7'

networks:
  default:
    external: true
    name: sagemaker-local

services:
  minio:
    image: minio/minio
    ports:
      - target: 9000 
        published: 9000
        mode: host
      - target: 9001
        published: 9001
        mode: host
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${DR_LOCAL_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${DR_LOCAL_SECRET_ACCESS_KEY}
      - MINIO_UID
      - MINIO_GID
      - MINIO_USERNAME
      - MINIO_GROUPNAME
    volumes:
      - ${DR_DIR}/data/minio:/data
